'use strict';

// AI adapter: when AI_BASE_URL + AI_API_KEY (+ optional AI_MODEL) are set,
// the personality narrative and archetype are generated by an OpenAI-compatible
// chat completions endpoint. Any failure falls back to the local engine, so the
// app never breaks when no key is configured.

const { TRAIT_LABELS, TAGS, WEEKEND, LOOKING } = require('./data');

function aiConfigured(env = process.env) {
  return Boolean(env.AI_API_KEY && (env.AI_BASE_URL || env.AI_OPENAI_COMPAT));
}

const SYSTEM_PROMPT = `You write personality blurbs for a bilingual Estonian-Russian social app called Venestlus.
Answer ONLY with valid JSON of the shape:
{"archetype":{"et":"...","ru":"..."},"summary":{"et":"...","ru":"..."}}
Rules: archetype is 1-3 words per language; summary is 2-3 natural sentences per language,
mentions the person's name, two strongest traits and one interest; tone is warm and concrete,
no emoji, no quotes around the JSON, no markdown.`;

function buildUserPrompt(p, labels) {
  const traits = Object.entries(p.traits)
    .map(([k, v]) => `${TRAIT_LABELS[k].et}=${v}`)
    .join(', ');
  const interests = p.interests.map((k) => `${TAGS[k].et} (${TAGS[k].ru})`).join(', ');
  return JSON.stringify({
    name: p.name,
    interests,
    traits,
    weekend: labels.weekend,
    looking: labels.looking,
    localArchetype: p.archetype,
    localSummary: p.summary,
  });
}

function valid(obj) {
  return obj
    && obj.archetype && typeof obj.archetype.et === 'string' && typeof obj.archetype.ru === 'string'
    && obj.summary && typeof obj.summary.et === 'string' && typeof obj.summary.ru === 'string'
    && obj.archetype.et.length <= 60 && obj.archetype.ru.length <= 60
    && obj.summary.et.length <= 600 && obj.summary.ru.length <= 600;
}

/**
 * Try the AI, return an upgraded personality or null.
 * Never throws.
 */
async function generate(answers, local, env = process.env) {
  if (!aiConfigured(env)) return null;
  // Fixture mode: lets tests and demos exercise the AI path without a real key.
  if (env.AI_MODE === 'fixture') {
    return {
      archetype: { et: 'Sild ehitaja', ru: 'Строитель мостов' },
      summary: {
        et: `${answers.name} ühendab keeli ja inimesi — AI-põhine näide.`,
        ru: `${answers.name} соединяет языки и людей — пример на основе ИИ.`,
      },
      traits: local.traits,
      interests: local.interests,
      ai: true,
    };
  }
  const url = `${(env.AI_BASE_URL || 'https://api.openai.com/v1').replace(/\/$/, '')}/chat/completions`;
  const labels = {
    weekend: WEEKEND[answers.weekend]?.et || answers.weekend,
    looking: LOOKING[answers.looking]?.et || answers.looking,
  };
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), Number(env.AI_TIMEOUT_MS) || 15000);
  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: `Bearer ${env.AI_API_KEY}`,
      },
      body: JSON.stringify({
        model: env.AI_MODEL || 'gpt-4o-mini',
        temperature: 0.7,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: buildUserPrompt({ ...answers, ...local }, labels) },
        ],
      }),
      signal: ctrl.signal,
    });
    if (!res.ok) {
      console.error(`[ai] http ${res.status}`);
      return null;
    }
    const data = await res.json();
    const text = data?.choices?.[0]?.message?.content;
    if (!text) return null;
    const parsed = JSON.parse(text);
    if (!valid(parsed)) {
      console.error('[ai] response failed validation, using local engine');
      return null;
    }
    return { archetype: parsed.archetype, summary: parsed.summary, traits: local.traits, interests: local.interests, ai: true };
  } catch (err) {
    console.error('[ai] fallback to local engine:', err.message);
    return null;
  } finally {
    clearTimeout(timer);
  }
}

module.exports = { aiConfigured, generate };
